### ISSUE TITLE
This is being used for IP grabbing and other nasty things

### ISSUE THREAD

**Issue by Zipdox** [5IGI0/FakeMinecraftServer#1]
This tool is being used by people to created thousands of hours of fake play time for famous players on IP grabbing servers on sites like minecraft-statistic.net. Do with this info what you want.

**Comment by 5IGI0** [comment]
it doesn't matter if smart people do this, they would have done it without my help.
and i don't think it's illegal in any country.

**Comment by telugu-boy** [comment]
fake

**Comment by tripulse** [comment]
:tm:
